name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: '21.3.0.java17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build Project
        run: |
          cd nearnstyle-apis
          mvn clean package -DskipTests 
        env:
          OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
          OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
          DATABASE_USERNAME: ${{ secrets.DB_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_URL: ${{ secrets.DB_URL }}
          OIDC_SERVER_URL: ${{ secrets.OIDC_SERVER_URL }}
          HTTP_PORT: ${{ secrets.HTTP_PORT }}
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: docker build -t mightythor99/nearnstyle-codebase .
      
      - name: Publish image to docker hub
        run: docker push mightythor99/nearnstyle-codebase:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Docker Info
        run: docker info
      
#      - name: Pull image from docker hub
#        run: docker pull mightythor99/nearnstyle-codebase
      
      - name: Delete old container
        run: docker rm -f nearnstyle-apis-container || true
      
      - name: Run docker container
        run: |
          docker run -d -p 8082:8082 \
          -e DATABASE_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DATABASE_URL=${{ secrets.DB_URL }} \
          -e OIDC_SERVER_URL=${{ secrets.OIDC_SERVER_URL }} \
          -e OIDC_CLIENT_ID=${{ secrets.OIDC_CLIENT_ID }} \
          -e OIDC_CLIENT_SECRET=${{ secrets.OIDC_CLIENT_SECRET }} \
          -e HTTP_PORT=${{ secrets.HTTP_PORT }} \
          --name nearnstyle-apis-container mightythor99/nearnstyle-codebase
